---
- name: Update apt package index
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: ['curl', 'gnupg', 'apt-transport-https']
    state: present

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and add Kubernetes signing key
  become: yes
  ansible.builtin.shell:
    cmd: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
  args:
    executable: /bin/bash


- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    update_cache: yes



- name: Install Kubernetes components
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
