---
- name: Initialize Kubernetes cluster
  hosts: controller
  become: yes
  tasks:
    - name: Stop Kubernetes cluster if running
      command: kubeadm reset -f

    - name: Initialize the Kubernetes cluster
      command: kubeadm init --pod-network-cidr=192.168.56.10/16 --apiserver-advertise-address=192.168.56.10
      register: kubeadm_init

    - name: Create .kube directory for admin user
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user's .kube directory
      shell: |
        cp -f /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config &&
        chown $(id -u {{ ansible_user }}):$(id -g {{ ansible_user }}) /home/{{ ansible_user }}/.kube/config

    - name: Get join token
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout }}" dest="/tmp/kubernetes_join_command" mode=0777

- name: Join worker nodes to the cluster
  hosts: node
  become: yes
  tasks:
    - name: Stop Kubernetes cluster if running
      command: kubeadm reset -f

    - name: Copy join command from Ansible host to the worker nodes.
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: '0777'

    - name: Join the Worker nodes to the cluster.
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - name: Create .kube directory for admin user
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy admin.conf to user's .kube directory
      shell: |
        cp -f /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config &&
        chown $(id -u {{ ansible_user }}):$(id -g {{ ansible_user }}) /home/{{ ansible_user }}/.kube/config
