- name: Install Helm and deploy Kubernetes Applications
  hosts: controller
  become: yes
  tasks:
    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add Prometheus Community Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Add Grafana Helm repository
      command: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Add Helm stable repository
      command: helm repo add stable https://charts.helm.sh/stable

    - name: Add Istio Helm repository
      command: helm repo add istio https://istio-release.storage.googleapis.com/charts

    - name: Add Kubernetes Dashboard Helm repository
      command: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/

    - name: Update Helm repositories
      command: helm repo update

    - name: Ensure Prometheus is not already installed
      shell: |
        helm list --filter '^prometheus$' -q | grep -q '^prometheus$' && helm uninstall prometheus || echo "Prometheus not installed"
      ignore_errors: yes

    - name: Install Prometheus
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      command: >
        helm upgrade -i prometheus prometheus-community/prometheus
        --set server.service.type=NodePort
        --set server.service.nodePort=30090
        --set server.service.port=9090
        --set server.global.scrape_interval=15s
        --set server.web.route-prefix=/prometheus
        --set server.web.external-url=http://192.168.56.10/prometheus

    - name: Install Grafana
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      command: helm upgrade -i grafana grafana/grafana --set service.type=NodePort --set adminPassword='admin' --set service.nodePort=30300 --set service.port=3000 --set grafana.grafana.ini.server.root_url='http://192.168.56.10/grafana' --set grafana.grafana.ini.server.serve_from_sub_path=true

    - name: Install Kubernetes Dashboard
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      command: helm upgrade -i kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --
