- name: Install Helm and deploy Kubernetes Applications
  hosts: controller
  become: yes
  tasks:
    - name: Install Helm
      get_url:
        url: https://get.helm.sh/helm-v3.7.2-linux-amd64.tar.gz
        dest: /tmp/helm-v3.7.2-linux-amd64.tar.gz

    - name: Extract Helm
      unarchive:
        src: /tmp/helm-v3.7.2-linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move Helm binary
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm

    - name: Add Prometheus Community Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

#    - name: Add Grafana Helm repository
#      command: helm repo add grafana https://grafana.github.io/helm-charts
#
#    - name: Add Helm stable repository
#      command: helm repo add stable https://charts.helm.sh/stable
#
#    - name: Add Istio Helm repository
#      command: helm repo add istio https://istio-release.storage.googleapis.com/charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Ensure Prometheus is not already installed
      shell: |
        helm list --filter '^prometheus$' -q | grep -q '^prometheus$' && helm uninstall prometheus || echo "Prometheus not installed"
      ignore_errors: yes

#    - name: Ensure Grafana is not already installed
#      shell: |
#        helm list --filter '^grafana$' -q | grep -q '^grafana$' && helm uninstall grafana || echo "Grafana not installed"
#      ignore_errors: yes
#
#    - name: Ensure Kubernetes Dashboard is not already installed
#      shell: |
#        helm list --filter '^kubernetes-dashboard$' -q | grep -q '^kubernetes-dashboard$' && helm uninstall kubernetes-dashboard || echo "Kubernetes Dashboard not installed"
#      ignore_errors: yes

    - name: Install Prometheus
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      command: helm upgrade -i prometheus prometheus-community/prometheus --set server.service.type=NodePort

#    - name: Install Grafana
#      environment:
#        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
#      command: helm upgrade -i grafana grafana/grafana --set service.type=NodePort --set adminPassword='admin' --set service.port=3000
#
#    - name: Install Kubernetes Dashboard
#      environment:
#        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
#      command: helm upgrade -i kubernetes-dashboard stable/kubernetes-dashboard --set service.type=NodePort --set service.externalPort=8080

    - name: Check if namespace exists
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      command: kubectl get namespaces istio-system
      register: namespace_check
      ignore_errors: yes

    - name: Create a namespace for Istio
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      command: kubectl create namespace istio-system
      when: namespace_check.rc != 0

    - name: Download Istio
      shell: curl -L https://istio.io/downloadIstio | sh -
      args:
        executable: /bin/bash

    - name: Install Istio
      shell: istio-1.22.0/bin/istioctl install --set profile=demo -y
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Label the namespace for Istio injection
      shell: kubectl label namespace default istio-injection=enabled
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml