- name: Install Istio
  hosts: controller
  become: yes
  tasks:
    - name: Export KUBECONFIG
      shell: export KUBECONFIG=/home/vagrant/.kube/config
    - name: Download Istio to home directory
      shell: curl -L https://istio.io/downloadIstio | sh -
    - name: Install Istio ctl
      shell: /home/vagrant/istio-1.22.1/bin/istioctl install -c /home/vagrant/.kube/config -y --set profile=demo

    - name: Enable Istio sidecar injection
      command: kubectl label namespace default istio-injection=enabled --overwrite