---
- name: Setup Kubernetes cluster
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - conntrack
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Add vagrant user to the Docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Download k3s
      get_url:
          url: https://github.com/k3s-io/k3s/releases/download/v1.30.0%2Bk3s1/k3s

    - name: Move k3s binary
      command: mv k3s /usr/local/bin/k3s
      args:
        creates: /usr/local/bin/k3s

    - name: Make k3s binary executable
      file:
          path: /usr/local/bin/k3s
          mode: '0755'

