apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: istio-system
data:
  config.yaml: |
    domain: istio-ratelimit
    descriptors:
      - key: generic_key
        value: request
        rate_limit:
          unit: minute
          requests_per_unit: 100
