---
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes

- name: Initialize the Kubernetes cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory for the vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Set up kubeconfig for the vagrant user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: /home/vagrant/.bashrc
    line: 'export KUBECONFIG=/home/vagrant/.kube/config'
    create: yes

- name: Source .bashrc to update environment variables
  shell: source /home/vagrant/.bashrc
  args:
    executable: /bin/bash

- name: Wait for the Kubernetes API server to be available
  shell: |
    while ! nc -z localhost 6443; do
      sleep 1
    done
  retries: 30
  delay: 10
  register: result
  until: result is succeeded
  args:
    executable: /bin/bash

- name: Install Calico network plugin
  shell: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: /home/vagrant/.kube/config
  args:
    executable: /bin/bash
