---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add Kubernetes apt-key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"
    force: true

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    update_cache: yes

- name: Install Kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true

- name: Install Kubeadm
  apt:
    name: kubeadm=1.29.*
    state: present

- name: Enable the Kubelet service
  service:
    name: kubelet
    enabled: yes

    ---
  - name: Add Kubernetes repository and key
    hosts: all
    become: yes
    tasks:
  - name: Ensure the directory for apt keyrings exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Add Kubernetes repository
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
      state: present
      filename: kubernetes

  - name: Download and add Kubernetes GPG key
    ansible.builtin.get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      mode: '0644'

  - name: Run apt-get update
    apt:
      update_cache: yes
