---
- hosts: controller
  become: true
  tasks:
    - name: Copy deployment and service manifests to controller
      copy:
        src: ../deployment/
        dest: /tmp/deployment/
        mode: 0644
        owner: root
        group: root

    - name: Apply frontend deployment and service
      shell: kubectl apply -f /tmp/deployment/frontend.yaml

    - name: Apply backend deployment and service
      shell: kubectl apply -f /tmp/deployment/backend.yaml

    - name: Apply model service deployment and service
      shell: kubectl apply -f /tmp/deployment/model-service.yaml
