---
- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=192.168.0.0/16

- name: Set up admin kubeconfig
  command: "{{ item }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Calico network
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
