---
- name: Retrieve join command from master
  shell: kubeadm token create --print-join-command
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  register: join_command

- name: Wait for the Kubernetes API server to be available
  shell: |
    while ! nc -z {{ hostvars[groups['controller'][0]].ansible_host }} 6443; do
      sleep 1
    done
  retries: 30
  delay: 10
  register: result
  until: result is succeeded
  args:
    executable: /bin/bash

- name: Join the cluster
  shell: "{{ join_command.stdout }}"
  when: join_command.stdout is defined
