apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/remla24-team12/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: MODEL_SERVICE_URL
            value: "http://192.168.56.10/model"
      nodeSelector:
        kubernetes.io/hostname: node-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/remla24-team12/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: VUE_APP_PUBLIC_PATH
            value: "/frontend/"
          - name: VUE_APP_API_URL
            value: "http://192.168.56.10/backend"
      nodeSelector:
        kubernetes.io/hostname: node-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
      - name: model-service
        image: ghcr.io/remla24-team12/model-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      nodeSelector:
        kubernetes.io/hostname: node-2